---
title: "Cloud Computing"
---

::: {.callout-note collapse="false"}
## CloudCourse.exe — Home

Welcome! This site contains weekly notes, examples, labs, and resources.


:::

## Sections

- [Lectures](#lectures) • [Labs](#labs) • [Homeworks](#homeworks)

## Lectures ([all](lectures.qmd)) {#lectures}

- [Lecture 1 — Cloud Big Picture](lecture1/index.qmd)
- [Lecture 2 — Firebase Deployment](lecture2/index.qmd)
- [Lecture 3 — Web Fundamentals](lecture3/index.qmd)
- [Lecture 4 — Authentication + Firestore](lecture4/index.qmd)
- [Lecture 5 — Git and GitHub](lecture5/index.qmd)
- [Lecture 6 — GitHub Actions](lecture6/index.qmd)
- [Lecture 7 — Docker](lecture7/index.qmd)
- [Lecture 8 — Jetstream2 (Research Cloud)](lecture8/index.qmd)
- [Lecture 9 — Stateful App & Security Concerns](lecture9/index.qmd)
- [Lecture 10 — OpenStack](lecture10/index.qmd)
- [Lecture 11 — The GCP Compute Continuum](lecture11/index.qmd)
- [Lecture 12 — The GCP Storage Continuum](lecture12/index.qmd)
- [Lecture 13 — Identity, Access, and the Zero-Trust Cloud](lecture13/index.qmd)
- [Lecture 14 — Automation, State, and Event-Driven Cloud](lecture14/index.qmd)
- [TL;DR — Recap](lecture15/index.qmd)


## Labs ([all](labs.qmd)) {#labs}

- [Lab 1 — Deploying a Simple App](lab1/index.qmd)
- [Lab 2 — Notes App](lab2/index.qmd)
- [Lab 3 — Forks, Pull Requests, Conflict Resolution](lab3/index.qmd)
- [Lab 4 — Dockerfile Swap](lab4/index.qmd)
- [Lab 5 — Jetstream2 Wildfire Simulator](lab5/index.qmd)
- [Lab 6 — Creating a VM via Terraform](lab6/index.qmd)
- [Lab 7 — Compute Engine and App Engine](lab7/index.qmd)
- [Lab 8 — Practicing Cloud Run](lab8/index.qmd)
- [Lab 9 — The Geology Zone (Dealing with Data)](lab9/index.qmd)
- [Lab 10 — Authentication With IAP](lab10/index.qmd)
- [Capstone Lab - Wave Function Collapse](lab11/index.qmd)

## Homeworks ([all](homeworks.qmd)) {#homeworks}

- [The Gatekeeper](homework1/index.qmd)
- [Midterm Project — Choose Your Own Adventure](project1/index.qmd)
- [Final Project — Orchestrating GCP](project2/index.qmd)
